### ISSUE TITLE
Update ressource error

### ISSUE THREAD

**Issue by alex4102** [brandlabs/productiveio#1]
Hello,

First of all thank you for your work.

But I don't know how to update ressource. I try this, but don't work :
`
$data = array("name" => "new name");
$productiveProject = $productiveApiClient->updateResource('deals', $payment->getProjectProductiveID(), $data);
`

Thanks for your help

**Comment by alex4102** [comment]
I fixed my problem by using :
`$data = array(
            "data" => array(
                "type" => "deals",
                "id" => $payment->getProjectProductiveID(),
                "attributes" => array(
                    "name" => "new name"
                )
            )
        );
`

**Comment by carsonreinke** [comment]
@alex4102 maybe we should update the documentation?

**Comment by alex4102** [comment]
I am not an expert with JSON API like this, maybe it's a beginner error :)
